const paletteData=[['奶白','#fffdf3'],['米黄','#f5dfad'],['柠黄','#ffd52f'],['橙黄','#ffad22'],['蜜桃','#ff946f'],['朱红','#e9463f'],['玫红','#e34177'],['粉红','#ffa1b6'],['浅紫','#bd9de8'],['紫罗兰','#7357b7'],['靛蓝','#3c54ae'],['湖蓝','#42a5d8'],['天空蓝','#8ed8ed'],['薄荷绿','#79d4b4'],['草绿','#61b84e'],['深绿','#258053'],['咖啡','#78503a'],['焦糖','#b7773c'],['浅灰','#c8c8c4'],['深灰','#555655'],['黑色','#202020'],['白色','#ffffff'],['肤色','#f3bf91'],['栗色','#9b463d']];
const canvas=document.querySelector('#beadCanvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});
const el=id=>document.getElementById(id);let gridW=32,gridH=32,beads=[],selected=paletteData[5],showGrid=true,zoom=1,history=[],imageLoaded=false;
function makeGrid(w=gridW,h=gridH){gridW=w;gridH=h;beads=Array.from({length:h},()=>Array(w).fill(null));history=[];render();}
function render(){const side=Math.min(720,Math.max(400,Math.min(gridW,gridH)*16));canvas.width=side;canvas.height=side;canvas.style.width=`${side*zoom}px`;canvas.style.height=`${side*zoom}px`;const cw=side/gridW,ch=side/gridH;ctx.fillStyle='#fff';ctx.fillRect(0,0,side,side);for(let y=0;y<gridH;y++)for(let x=0;x<gridW;x++){ctx.fillStyle=beads[y][x]?.[1]||'#fff';ctx.fillRect(x*cw,y*ch,cw,ch)}if(showGrid){ctx.strokeStyle='#d5d3cc';ctx.lineWidth=Math.max(.45,side/900);ctx.beginPath();for(let x=0;x<=gridW;x++){ctx.moveTo(x*cw,0);ctx.lineTo(x*cw,side)}for(let y=0;y<=gridH;y++){ctx.moveTo(0,y*ch);ctx.lineTo(side,y*ch)}ctx.stroke()}updateStats();el('gridInfo').textContent=`${gridW} × ${gridH} 格`;}
function updateStats(){const list=beads.flat().filter(Boolean);el('beadTotal').textContent=list.length;el('usedColors').textContent=new Set(list.map(c=>c[0])).size;}
function drawAt(e){if(!beads.length)return;const rect=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-rect.left)/rect.width*gridW),y=Math.floor((e.clientY-rect.top)/rect.height*gridH);if(x<0||y<0||x>=gridW||y>=gridH)return;if(!history.length||history.at(-1)!==beads)history.push(beads.map(r=>r.slice()));beads[y][x]=selected;render();}
canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);drawAt(e)});canvas.addEventListener('pointermove',e=>{if(e.buttons)drawAt(e)});
function buildPalette(){el('palette').innerHTML='';paletteData.forEach(c=>{const b=document.createElement('button');b.className='swatch'+(c===selected?' selected':'');b.style.background=c[1];b.title=c[0];b.onclick=()=>{selected=c;buildPalette()};el('palette').append(b)});}
function activate(mode){document.querySelectorAll('.mode').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));document.querySelector('.image-panel').style.display=mode==='image'?'block':'none';if(mode==='create'&&!beads.length){makeGrid(+el('gridWidth').value,+el('gridHeight').value);el('emptyState').classList.add('hidden');el('projectTitle').textContent='自由创作';}}
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>activate(b.dataset.mode));el('startCreate').onclick=()=>activate('create');
document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{const s=+b.dataset.size;el('gridWidth').value=s;el('gridHeight').value=s;document.querySelectorAll('[data-size]').forEach(x=>x.classList.toggle('selected',x===b));if(beads.length)makeGrid(s,s)});
['gridWidth','gridHeight'].forEach(id=>el(id).addEventListener('change',()=>{if(beads.length)makeGrid(+el('gridWidth').value,+el('gridHeight').value)}));el('colorCount').oninput=e=>el('colorCountValue').textContent=`${e.target.value} 色`;el('gridBtn').onclick=()=>{showGrid=!showGrid;el('gridBtn').classList.toggle('active',showGrid);render()};el('zoomIn').onclick=()=>{zoom=Math.min(1.7,zoom+.15);el('zoomLabel').textContent=`${Math.round(zoom*100)}%`;render()};el('zoomOut').onclick=()=>{zoom=Math.max(.55,zoom-.15);el('zoomLabel').textContent=`${Math.round(zoom*100)}%`;render()};el('undoBtn').onclick=()=>{if(history.length){beads=history.pop();render()}};
function nearest(rgb,colors){let best=colors[0],score=Infinity;colors.forEach(c=>{const h=c[1].slice(1),q=[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4),16)],d=q.reduce((s,v,i)=>s+(v-rgb[i])**2,0);if(d<score){score=d;best=c}});return best}
el('imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const img=new Image();img.onload=()=>{el('imagePreview').src=img.src;el('previewWrap').classList.remove('hidden');document.querySelector('.upload-zone').classList.add('hidden');convertImage(img)};img.src=URL.createObjectURL(f)};
function convertImage(img){const w=+el('gridWidth').value,h=+el('gridHeight').value,n=+el('colorCount').value,tmp=document.createElement('canvas');tmp.width=w;tmp.height=h;tmp.getContext('2d').drawImage(img,0,0,w,h);const data=tmp.getContext('2d').getImageData(0,0,w,h).data;gridW=w;gridH=h;beads=Array.from({length:h},(_,y)=>Array.from({length:w},(_,x)=>nearest([data[(y*w+x)*4],data[(y*w+x)*4+1],data[(y*w+x)*4+2]],paletteData.slice(0,n))));imageLoaded=true;el('emptyState').classList.add('hidden');el('projectTitle').textContent='图片转拼豆图纸';render();toast('已生成拼豆图纸，可继续调整颜色')}
el('removeImage').onclick=()=>{el('imageInput').value='';el('previewWrap').classList.add('hidden');document.querySelector('.upload-zone').classList.remove('hidden')};
el('clearBtn').onclick=()=>{if(beads.length){makeGrid(gridW,gridH);toast('画布已清空')}};el('saveBtn').onclick=()=>{if(!beads.length){toast('请先创建或生成图纸');return}const link=document.createElement('a');link.download='拼豆图纸.png';link.href=canvas.toDataURL('image/png');link.click();toast('图纸已导出')};function toast(s){el('toast').textContent=s;el('toast').classList.add('show');setTimeout(()=>el('toast').classList.remove('show'),2200)}buildPalette();
